# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: push                             # event trigger on push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # Job ID: 문자와 -(대시), _(언더바)로 구성된 Job 고유 식별자
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # env: MONGO_URI:${{ secrets.MONGO_URI}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2 # 소스코드 checkout
      - name: checkout source code # step 01 이름
        run: echo "hello world1" # linux command 실행

      - name: say hello # step 02 이름
        run: echo "hello world" # linux command 실행
